spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furamaresort?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 18112001
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
